# Generated by Django 3.1.2 on 2021-01-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0004_auto_20210104_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
